global:
  scrape_interval: 5s
  external_labels:
    monitor: 'system-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.17.0.1:9100']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['172.17.0.1:8080']
    tls_config:
      insecure_skip_verify: true
